backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploads
media_library:
  name: cloudinary
  config: 
    cloud_name: mugas
    api_key: 337512876763955
public_folder: "/images/uploads"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: "json"
    sort: "date:desc" # Default is title:asc
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "start",
          format: "LL",
          widget: "datetime",
          dateformat: "DD.MMM.YYYY",
        }
      - { label: "Author", name: "author", widget: "string" }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - {
          label: "Excerpt",
          name: "excerpt",
          widget: "string",
          required: true,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list"}
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Projects" # Used in the UI
    folder: "content/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: "json"
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: 'Description', name: 'description', widget: 'text'}
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { label: "body", name: "body", widget: "markdown",}
      - {
          label: "Excerpt",
          name: "excerpt",
          widget: "string",
          required: true,
        }
  - name: "setup"
    label: "Setup"
    files:
      - label: "Site Info"
        name: "info"
        format: "json"
        file: "content/setup/info.json"
        fields:
          - { label: Site Name, name: sitename, widget: string }
          - { label: Site Description, name: sitedescription, widget: string }
  - name: "about"
    label: "About"
    files:
      - label: "About"
        name: "about"
        format: "json"
        file: "content/about/about-me.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: string }
          - { label: Featured Image, name: thumbnail, widget: image }
