<template lang="html" class="homepage">
<TheHeader/>

   <!-- <div class="main">
      <h1><span class="slide-in-top">L</span><span class="slide-in-top">oo</span>king <span class="slide-in-top">f</span>or Me?</h1>
      <h2 class="bounce-in-top-fast slide-in-top">I create things and stuff</h2>
  </div> -->

  <div class="main">
    <h1><span class="bounce-in-top-second">L</span><span class="bounce-in-top-third">oo</span><span class="letter-k">k</span><span class="king-word">ing</span> <span class="bounce-in-top-first">f</span>or Me<span class="question-mark">?</span><span class="exclamation">!</span></h1>

    <p>I create things and stuff</p>
  </div>        

</template>


<script>
import TheHeader from '../components/TheHeader/TheHeader'
export default {
  components:{
    TheHeader
  }
}
</script>



<style lang="css" scoped>

* {
  box-sizing: border-box;
  padding: 0;
  margin: 0;
  padding-top: 10px;
}

 html,body{
  margin: 0;
  padding: 0;
}

h1{
 text-align:center;
 font-size:150px;
}

.letter-k{
color:#A64E43 ;
}
.king-word{
  color:#A64E43;
}

.exclamation{
  color:#A64E43;
  webkit-animation: swing-out-bottom-bck 3.2s 11.1s cubic-bezier(0.600, -0.280, 0.735, 0.045) both;
	        animation: swing-out-bottom-bck 3.2s 11.1s cubic-bezier(0.600, -0.280, 0.735, 0.045) both;
          display: inline-block;   
}

.question-mark{
  color:#A64E43;
      -webkit-animation: bounce-in-top 1s 11s both;
  animation: bounce-in-top 1s 11s both;
  display: inline-block;   
}
 
 
.bounce-in-top-first{
  -webkit-animation: bounce-in-top 7.1s both;
  animation: bounce-in-top 7.1s both;
  display: inline-block;     
  color:#20263F;
}

.bounce-in-top-second {
	-webkit-animation: bounce-in-top 10.1s both;
	animation: bounce-in-top 10.1s both;
  display: inline-block;
  color:#20263F;
}

.bounce-in-top-third {
	-webkit-animation: bounce-in-top 1s 10s both;
	animation: bounce-in-top 1s 10s both;
  display: inline-block;
  color:#C8882D;
}


/* ----------------------------------------------
 * Generated by Animista on 2020-7-8 8:27:13
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation swing-out-bottom-bck
 * ----------------------------------------
 */
@-webkit-keyframes swing-out-bottom-bck {
  0% {
    -webkit-transform: rotateX(0);
            transform: rotateX(0);
    -webkit-transform-origin: bottom;
            transform-origin: bottom;
    opacity: 1;
  }
  100% {
    -webkit-transform: rotateX(100deg);
            transform: rotateX(100deg);
    -webkit-transform-origin: bottom;
            transform-origin: bottom;
    opacity: 0;
  }
}
@keyframes swing-out-bottom-bck {
  0% {
    -webkit-transform: rotateX(0);
            transform: rotateX(0);
    -webkit-transform-origin: bottom;
            transform-origin: bottom;
    opacity: 1;
  }
  100% {
    -webkit-transform: rotateX(100deg);
            transform: rotateX(100deg);
    -webkit-transform-origin: bottom;
            transform-origin: bottom;
    opacity: 0;
  }
 


}



/**
 * ----------------------------------------
 * animation bounce-in-top
 * ----------------------------------------
 */
@-webkit-keyframes bounce-in-top {
  0% {
    -webkit-transform: translateY(-500px);
            transform: translateY(-500px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
    opacity: 0;
  }
  38% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
    opacity: 1;
  }
  55% {
    -webkit-transform: translateY(-65px);
            transform: translateY(-65px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  72% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  81% {
    -webkit-transform: translateY(-28px);
            transform: translateY(-28px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  90% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  95% {
    -webkit-transform: translateY(-8px);
            transform: translateY(-8px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
}
@keyframes bounce-in-top {
  0% {
    -webkit-transform: translateY(-500px);
            transform: translateY(-500px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
    opacity: 0;
  }
  38% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
    opacity: 1;
  }
  55% {
    -webkit-transform: translateY(-65px);
            transform: translateY(-65px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  72% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  81% {
    -webkit-transform: translateY(-28px);
            transform: translateY(-28px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  90% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  95% {
    -webkit-transform: translateY(-8px);
            transform: translateY(-8px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
}


</style>
